In [1]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings("ignore")

In [2]:
def generate_subject_form(folderPath, outputPath):
    adsh_lst = []
    
    fileName_lst = os.listdir(folderPath)
    riskFactorSubject_lst = []
    for fileName in fileName_lst:
        adsh = fileName.rstrip(".txt")
        filePath = str(folderPath) + str(fileName)    
        with open(filePath, 'r', encoding='utf-8') as file:
            fileText = file.read()
    
        subject = fileText.split('\n')
        riskFactorSubject_lst.extend(subject)
        adsh_lst.extend([adsh] * len(subject))
    df = pd.DataFrame(list(zip(adsh_lst, riskFactorSubject_lst)), columns=['adsh', 'Risk Factors'])
    df.to_csv(outputPath, index=False)
    return df

## 1. Bank Industry

In [3]:
_6021FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Bank Industry/Industry_6021/Subject/"
_6021OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_6021.csv"
_6021_df = generate_subject_form(_6021FolderPath, _6021OutputPath)
_6021_df.head()

                   adsh                                       Risk Factors
0  0000036966-23-000016             Risks Related to the Pending TD Merger
1  0000036966-23-000016  Receipt of regulatory approvals for the Pendin...
2  0000036966-23-000016  Regulatory approvals may not be received, have...
3  0000036966-23-000016  The TD Merger Agreement may be terminated in a...
4  0000036966-23-000016  Failure to complete the Pending TD Merger coul...

In [4]:
_6022FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Bank Industry/Industry_6022/Subject/"
_6022OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_6022.csv"
_6022_df = generate_subject_form(_6022FolderPath, _6022OutputPath)
_6022_df.head()

                   adsh                                       Risk Factors
0  0000007789-23-000013                                       Credit Risks
1  0000007789-23-000013  Changes and instability in economic conditions...
2  0000007789-23-000013  Changes in U.S. trade policies, including the ...
3  0000007789-23-000013  Our allowance for credit losses may be insuffi...
4  0000007789-23-000013     We are subject to lending concentration risks.

## 2. Energy Industry

In [25]:
_1311FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Energy Industry/Industry_1311/Subject/"
_1311OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_1311.csv"
_1311_df = generate_subject_form(_1311FolderPath, _1311OutputPath)
_1311_df.head()

                   adsh                                       Risk Factors
0  0000007332-23-000005  Natural gas, oil and NGL prices and basis diff...
1  0000007332-23-000005  Significant capital investment is required to ...
2  0000007332-23-000005  If we are not able to develop and replace rese...
3  0000007332-23-000005  Our business depends on access to natural gas,...
4  0000007332-23-000005  Strategic determinations, including the alloca...

In [27]:
_1389FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Energy Industry/Industry_1389/Subject/"
_1389OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_1389.csv"
_1389_df = generate_subject_form(_1389FolderPath, _1389OutputPath)
_1389_df.head()

                   adsh                                       Risk Factors
0  0000950170-23-002412  Risk factors associated with the industry in w...
1  0000950170-23-002412  Events beyond Core Lab’s control, including a ...
2  0000950170-23-002412  Any cost reduction initiatives that Core Lab u...
3  0000950170-23-002412  Downturns in the oil and gas industry, or in t...
4  0000950170-23-002412  Changes in macro-economic factors impacting th...

In [31]:
_4911FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Energy Industry/Industry_4911/Subject/"
_4911OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_4911.csv"
_4911_df = generate_subject_form(_4911FolderPath, _4911OutputPath)
_4911_df.head()

                   adsh                                       Risk Factors
0  0000004904-23-000011              GENERAL RISKS OF REGULATED OPERATIONS
1  0000004904-23-000011  AEP may not be able to recover the costs of su...
2  0000004904-23-000011  Regulated electric revenues and earnings are d...
3  0000004904-23-000011  AEP’s transmission investment strategy and exe...
4  0000004904-23-000011  Certain elements of AEP’s transmission formula...

## 3. Life Sciences Industry

In [5]:
_2834FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Life Sciences Industry/Industry_2834/Subject/"
_2834OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_2834.csv"
_2834_df = generate_subject_form(_2834FolderPath, _2834OutputPath)
_2834_df.head()

                   adsh                                       Risk Factors
0  0000014272-23-000046            Product, Industry and Operational Risks
1  0000014272-23-000046  Increased pricing pressure and other restricti...
2  0000014272-23-000046  We may experience difficulties or delays in th...
3  0000014272-23-000046  We could lose market exclusivity of a product ...
4  0000014272-23-000046  We face intense competition from other manufac...

In [6]:
_2836FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Life Sciences Industry/Industry_2836/Subject/"
_2836OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_2836.csv"
_2836_df = generate_subject_form(_2836FolderPath, _2836OutputPath)
_2836_df.head()

                   adsh                                       Risk Factors
0  0000819050-23-000037           Risks Related to Our Business Operations
1  0000819050-23-000037  Our business depends on the successful continu...
2  0000819050-23-000037  Clinical drug development for our pipeline ass...
3  0000819050-23-000037  Major public health issues, and specifically t...
4  0000819050-23-000037  Our product candidates may not achieve adequat...

## 4. Real Estate Industry

In [35]:
_6500FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Real Estate Industry/Industry_6500/Subject/"
_6500OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_6500.csv"
_6500_df = generate_subject_form(_6500FolderPath, _6500OutputPath)
_6500_df.head()

                   adsh                                       Risk Factors
0  0000096869-23-000006                                    STRATEGIC RISKS
1  0000096869-23-000006  Adverse changes in economic conditions in mark...
2  0000096869-23-000006  Higher interest rates and lack of available fi...
3  0000096869-23-000006  We are subject to various land use regulations...
4  0000096869-23-000006  Third-party litigation could increase the time...

In [37]:
_6798FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Real Estate Industry/Industry_6798/Subject/"
_6798OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_6798.csv"
_6798_df = generate_subject_form(_6798FolderPath, _6798OutputPath)
_6798_df.head()

                   adsh                                       Risk Factors
0  0000014846-23-000005  Risks Related to Real Estate Investments and O...
1  0000014846-23-000005  Unfavorable market and economic conditions cou...
2  0000014846-23-000005  Increasing real estate taxes, utilities and in...
3  0000014846-23-000005  Most of our multi-family properties are locate...
4  0000014846-23-000005  We may be unable to compete to acquire, financ...

## 5. Technology Service Industry

In [22]:
_7370FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Technology Service Industry/Industry_7370/Subject/"
_7370OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_7370.csv"
_7370_df = generate_subject_form(_7370FolderPath, _7370OutputPath)
_7370_df.head()

                   adsh                                       Risk Factors
0  0000746210-23-000011                      Risks Related to Our Business
1  0000746210-23-000011  Our Company experienced declines in revenue in...
2  0000746210-23-000011  Revenue growth and increase in the market shar...
3  0000746210-23-000011  We have a history of substantial net operating...
4  0000746210-23-000011  Our business activities will require additiona...

In [10]:
_7372FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Technology Service Industry/Industry_7372/Subject/"
_7372OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_7372.csv"
_7372_df = generate_subject_form(_7372FolderPath, _7372OutputPath)
_7372_df.head()

                   adsh                                       Risk Factors
0  0000813672-23-000011                     Business and Operational Risks
1  0000813672-23-000011  We have experienced varied operating results, ...
2  0000813672-23-000011  Any periods of uncertainty in the global econo...
3  0000813672-23-000011  We are subject to governmental export and impo...
4  0000813672-23-000011  As we acquire and invest in companies or techn...

In [23]:
_7374FolderPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Technology Service Industry/Industry_7374/Subject/"
_7374OutputPath = "E:/Jupyter Notebook Files/ISE 540_Text Analytics/Project/Risk Factor Text/Risk Factor Subject Text Summary/Subject_7374.csv"
_7374_df = generate_subject_form(_7374FolderPath, _7374OutputPath)
_7374_df.head()

                   adsh                                       Risk Factors
0  0000008670-22-000038                         LEGAL AND COMPLIANCE RISKS
1  0000008670-22-000038  Failure to comply with, or changes in, laws an...
2  0000008670-22-000038  Failure to comply with anti-corruption laws an...
3  0000008670-22-000038  Failure to comply with privacy, data protectio...
4  0000008670-22-000038  If we fail to protect our intellectual propert...